#!/bin/bash
sshusername=""
sshpassword=""
sshport=""
wwwusername=""
wwwpassword=""
url=""
rx='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'

wget -q --post-data 'user='$wwwusername'&pw='$wwwpassword'' $url -O ~/routerlist.php;
lynx --dump -center -width=100 ~/routerlist.php |cut -d' ' -f4-5 |head -n -4 |tail -n +11 |tr '[:upper:]' '[:lower:]' > ~/.hosts
sed -i 's/-//g;s/master/1/g;s/backup/2/g;s/slave/2/g;s/block//g' ~/.hosts
lynx --dump -center -width=100 ~/routerlist.php |cut -d' ' -f5-5 |head -n -4 |tail -n +11 |sed ':a;N;$!ba;s/\n/ /g' > ~/.mtkip
rm ~/routerlist.php

export HOSTALIASES=~/.hosts
echo "MikroTik IP or site CODE please:"
read ip
if grep -Fwq $ip ~/.hosts ||[[ $ip =~ ^$rx\.$rx\.$rx\.$rx$ ]]
then sshpass -p $sshpassword ssh -p $sshport -t -t -o StrictHostKeyChecking=no $sshusername@$ip
else grep $ip -F ~/.hosts
mtk
fi
